'use client';
import {useEffect,useState,type ReactNode,type FormEvent} from 'react';
import {LockKeyhole} from 'lucide-react';
export function AuthGate({children}:{children:ReactNode}) {const [status,setStatus]=useState<'loading'|'login'|'setup'|'ready'|'error'>('loading');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
async function check(){try{const r=await fetch('/api/auth',{cache:'no-store'});const d=await r.json() as {error:string;authenticated?:boolean;setup?:boolean};if(!r.ok)throw new Error(d.error);setStatus(d.authenticated?'ready':d.setup?'setup':'login');setError('');}catch{setError('לא ניתן להתחבר לשירות כרגע.');setStatus('error');}}
useEffect(()=>{void check();},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(status==='setup'&&data.get('password')!==data.get('confirm')){setError('הסיסמאות אינן תואמות.');return;}setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(data))});const d=await r.json() as {error:string;authenticated?:boolean;setup?:boolean};if(!r.ok)throw new Error(d.error);setStatus('ready');}catch(e){setError(e instanceof Error?e.message:'לא ניתן להתחבר');}finally{setBusy(false);}}
if(status==='ready')return children;
return <main className="auth-shell" dir="rtl"><div className="auth-brand">Life OS <span>המרחב האישי שלך</span></div><section className="auth-panel"><LockKeyhole size={30}/><h1>{status==='setup'?'מקום אחד. רק שלך.':'טוב שחזרת.'}</h1><p>{status==='setup'?'הזן את קוד ההפעלה הפרטי ובחר סיסמה. ההפעלה נדרשת פעם אחת בלבד.':'התחבר כדי לראות את המשימות, ההרגלים והנתונים שלך.'}</p>{status==='loading'?<p role="status">מתחבר…</p>:status==='error'?<button className="primary-action" onClick={check}>נסה שוב</button>:<form onSubmit={submit} className="life-form">{status==='setup'&&<label>קוד הפעלה<input name="setupToken" required autoComplete="off" type="password"/></label>}<label>סיסמה<input name="password" type="password" required minLength={12} maxLength={256} autoComplete={status==='setup'?'new-password':'current-password'}/></label>{status==='setup'&&<label>הקלד שוב את הסיסמה<input name="confirm" type="password" required minLength={12} autoComplete="new-password"/></label>}<button className="primary-action" disabled={busy}>{busy?'מתחבר…':status==='setup'?'פתיחת המרחב שלי':'כניסה'}</button></form>}{error&&<p role="alert" className="form-error">{error}</p>}</section></main>;}
