'use client';
import {useState,type ReactNode,type SubmitEvent} from 'react';import {Trash2} from 'lucide-react';import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {useLife} from './use-life';
// The app's one modal surface: centred glass, and on a phone a sheet that rises
// from the bottom edge (.life-editor in globals.css). It owns its open state, so
// a close plays the exit before the parent unmounts it; `locked` holds it open
// against Escape and outside presses, as while a save is in flight.
export function Sheet({title,onClose,locked=false,children}:{title:string;onClose:()=>void;locked?:boolean;children:(close:()=>void)=>ReactNode}){const [open,setOpen]=useState(true);const close=()=>setOpen(false);
return <Dialog open={open} onOpenChange={next=>{if(!next&&!locked)close();}} onOpenChangeComplete={next=>{if(!next)onClose();}}><DialogContent className="life-editor" showCloseButton={false}><DialogTitle className="text-xl font-semibold">{title}</DialogTitle>{children(close)}</DialogContent></Dialog>;}
export function Editor({title,children,onClose,onSave,onDelete}:{title:string;children:ReactNode;onClose:()=>void;onSave:(form:FormData)=>Promise<unknown>;onDelete?:()=>void}){const {busy}=useLife();const [error,setError]=useState('');
return <Sheet title={title} onClose={onClose} locked={busy}>{close=>{async function submit(e:SubmitEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setError('');try{await onSave(data);close();}catch(e){setError(e instanceof Error?e.message:'לא ניתן לשמור. נסה שוב.');}}
return <><DialogDescription className="sr-only">מלא את הפרטים ושמור את השינויים</DialogDescription><form className="life-form" onSubmit={submit}><fieldset disabled={busy} className="contents">{children}</fieldset>{error&&<p role="alert" className="form-error">{error}</p>}<footer className="editor-actions"><button className="primary-action" disabled={busy}>{busy?'שומר…':'שמירה'}</button><button type="button" className="quiet-action" disabled={busy} onClick={close}>ביטול</button>{onDelete&&<button type="button" className="icon-action danger editor-delete" disabled={busy} aria-label="מחיקה" onClick={()=>{onDelete();close();}}><Trash2 size={16}/></button>}</footer></form></>;}}</Sheet>;}
export function Field({label,children}:{label:string;children:ReactNode}){return <label>{label}{children}</label>;}
export const field=(form:FormData,key:string)=>{const value=form.get(key);return typeof value==='string'?value.trim():'';};
export function Empty({title,text,action,onAction}:{title:string;text:string;action?:string;onAction?:()=>void}){return <div className="life-empty"><h3>{title}</h3><p>{text}</p>{action&&<button className="quiet-action" onClick={onAction}>{action}</button>}</div>;}
