'use client';
import {useState} from 'react';import {Check,Pencil,Plus,Trash2,Flame} from 'lucide-react';import {todayKey,dateOffset,scheduled,streak,type Entry} from '@/lib/life-model';import {select,useLife} from './use-life';import {Editor,Field,Empty,field} from './editor';
const days=['א׳','ב׳','ג׳','ד׳','ה׳','ו׳','ש׳'];
export function HabitsView({compact=false}:{compact?:boolean}){const {records,save,busy}=useLife();const today=todayKey();const [date,setDate]=useState(today),[editing,setEditing]=useState<Entry<'habit'>|null|undefined>();const habits=select(records,'habit'),entries=select(records,'habitEntry');const visible=compact?habits.filter(h=>scheduled(h.data,today)):habits;const selected=compact?today:date;
async function toggle(h:Entry<'habit'>,day:string){const id='entry:'+h.id+':'+day;const old=records.find(e=>e.id===id) as Entry<'habitEntry'>|undefined;await save('habitEntry',{habitId:h.id,date:day,done:!(old&&!old.deletedAt&&old.data.done)},old,id);}
return <section><header className="module-header"><div><h2>{compact?'ההרגלים של היום':'עקביות, בקצב שלך'}</h2><p>{compact?'כל סימון הוא צעד קטן קדימה.':'ימי ביצוע, היסטוריה ורצף אישי.'}</p></div><button className="quiet-action" onClick={()=>setEditing(null)}><Plus size={17}/>הרגל חדש</button></header>{!compact&&<label className="date-control">יום לתיעוד<input aria-label="יום לתיעוד" type="date" value={date} max={today} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label>}
{visible.map(h=>{const done=entries.some(e=>e.data.habitId===h.id&&e.data.date===selected&&e.data.done),due=scheduled(h.data,selected);return <div key={h.id} className="habit-record"><div className="record-row"><span className="habit-emoji">{h.data.emoji}</span><div className="record-body"><p>{h.data.title}</p><small><Flame size={13} className="inline"/> {streak(h,entries,today)} ימי ביצוע ברצף · {h.data.days.map(d=>days[d]).join(' ')}</small></div><button aria-label={(done?'ביטול סימון ':'סימון ')+h.data.title} aria-pressed={done} disabled={busy||!due||selected>today} className={'habit-mark '+(done?'checked':'')} onClick={()=>{void toggle(h,selected).catch(()=>{});}}>{done?<Check size={17}/>:due?'סימון':'יום מנוחה'}</button><button className="icon-action" aria-label={'עריכת '+h.data.title} onClick={()=>setEditing(h)}><Pencil size={16}/></button>{!compact&&<button className="icon-action" disabled={busy} aria-label={'מחיקת '+h.data.title} onClick={()=>{void save('habit',h.data,h,undefined,true).catch(()=>{});}}><Trash2 size={16}/></button>}</div>{!compact&&<div className="habit-history" aria-label={'שבוע אחרון: '+h.data.title}>{Array.from({length:7},(_,i)=>dateOffset(selected,i-6)).map(day=>{const marked=entries.some(e=>e.data.habitId===h.id&&e.data.date===day&&e.data.done);return <button key={day} className={marked?'marked':''} aria-label={h.data.title+' '+day+(marked?' בוצע':' לא בוצע')} aria-pressed={marked} disabled={busy||day>today||!scheduled(h.data,day)} onClick={()=>{void toggle(h,day).catch(()=>{});}}><span>{new Date(day+'T12:00:00Z').toLocaleDateString('he-IL',{weekday:'short'})}</span><b>{marked?<Check size={16}/>:new Date(day+'T12:00:00Z').getUTCDate()}</b></button>;})}</div>}</div>;})}
{!visible.length&&<Empty title={habits.length?'יום פנוי מהרגלים':'הרגל קטן, התחלה טובה'} text={habits.length?'אין הרגלים מתוכננים להיום.':'בחר משהו שתרצה לעשות באופן קבוע.'} action="הוספת הרגל" onAction={()=>setEditing(null)}/>}
{editing!==undefined&&<Editor title={editing?'עריכת הרגל':'הרגל חדש'} onClose={()=>setEditing(undefined)} onSave={f=>save('habit',{title:field(f,'title'),emoji:field(f,'emoji'),startDate:field(f,'startDate'),days:f.getAll('days').map(Number)},editing||undefined)}><Field label="שם ההרגל"><input name="title" required maxLength={200} defaultValue={editing?.data.title}/></Field><div className="form-columns"><Field label="סמל"><select name="emoji" defaultValue={editing?.data.emoji||'🌱'}>{['🌱','💧','📚','🚶','🧘','🏃','💪','🛌'].map(e=><option key={e}>{e}</option>)}</select></Field><Field label="תאריך התחלה"><input name="startDate" type="date" required max={today} defaultValue={editing?.data.startDate||today}/></Field></div><fieldset className="day-picker"><legend>באילו ימים?</legend>{days.map((d,i)=><label key={i}><input type="checkbox" name="days" value={i} defaultChecked={editing?editing.data.days.includes(i):true}/><span>{d}</span></label>)}</fieldset></Editor>}</section>;}
