'use client';
import { useEffect, useState } from 'react';
import { ArrowDownLeft, ArrowUpLeft, Check, ChevronLeft, CircleDollarSign, Flame, Home, ListTodo, Plus, Target, Timeline, Utensils, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';

type Task={id:string;title:string;time?:string;done:boolean};
type Habit={id:string;title:string;emoji:string;streak:number;done:boolean};
const seedTasks:Task[]=[{id:'t1',title:'לעבור על תקציב ספטמבר',time:'10:00',done:false},{id:'t2',title:'לקבוע תור לרופא שיניים',done:false},{id:'t3',title:'לשלוח סיכום שבועי',time:'16:30',done:true}];
const seedHabits:Habit[]=[{id:'h1',title:'שתיית מים',emoji:'💧',streak:12,done:true},{id:'h2',title:'קריאה 20 דק׳',emoji:'📚',streak:7,done:false},{id:'h3',title:'הליכה',emoji:'🚶',streak:4,done:false}];
const activity=[{icon:Utensils,title:'ארוחת צהריים',detail:'אוכל · לפני 24 דקות',value:'− ₪45',tone:'orange'},{icon:Check,title:'שלחת סיכום שבועי',detail:'משימה · 09:45',value:'הושלם',tone:'green'},{icon:Flame,title:'שתיית מים',detail:'הרגל · רצף של 12 ימים',value:'+1',tone:'blue'}];

export default function HomePage(){
 const[tasks,setTasks]=useState(seedTasks);const[habits,setHabits]=useState(seedHabits);const[notice,setNotice]=useState('');
 const completed=tasks.filter(x=>x.done).length,habitDone=habits.filter(x=>x.done).length;
 const toggleTask=(id:string)=>setTasks(xs=>xs.map(x=>x.id===id?{...x,done:!x.done}:x));
 const toggleHabit=(id:string)=>setHabits(xs=>xs.map(x=>x.id===id?{...x,done:!x.done}:x));
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool?:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'complete_today_task',title:'סימון משימה כהושלמה',description:'Marks a visible task as completed by task id.',inputSchema:{type:'object',properties:{taskId:{type:'string'}},required:['taskId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const taskId=(input as{taskId?:string}).taskId;if(!tasks.some(x=>x.id===taskId))throw new Error('Task not found');setTasks(xs=>xs.map(x=>x.id===taskId?{...x,done:true}:x));return{taskId,status:'completed'}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[tasks]);
 return <div dir="rtl" className="min-h-screen bg-[#f4f2ec] text-[#18211f] selection:bg-[#b7dfd2]"><div className="mx-auto min-h-screen max-w-[1180px] lg:grid lg:grid-cols-[240px_1fr] lg:gap-8 lg:px-7">
  <aside className="hidden py-7 lg:flex lg:flex-col"><div className="mb-10 flex items-center gap-3 px-3"><div className="grid size-10 place-items-center rounded-2xl bg-[#173f3a] text-lg font-black text-white">L</div><div><p className="text-lg font-extrabold">Life OS</p><p className="text-xs text-[#71807c]">הכל במקום אחד</p></div></div><nav className="space-y-2" aria-label="ניווט ראשי">{[[Home,'היום',true],[WalletCards,'כספים'],[ListTodo,'משימות'],[Flame,'הרגלים'],[Target,'מטרות'],[Timeline,'ציר הזמן']].map(([Icon,label,active])=><button key={String(label)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-sm font-semibold ${active?'bg-[#173f3a] text-white shadow-sm':'text-[#5d6b67] hover:bg-white'}`}><Icon className="size-5"/>{String(label)}</button>)}</nav><div className="mt-auto rounded-[24px] bg-[#dfece6] p-5"><p className="text-xs font-bold text-[#46635b]">טיפ יומי</p><p className="mt-2 text-sm leading-6">עדכון קטן בכל יום הופך את התמונה הגדולה לברורה.</p></div></aside>
  <main className="min-w-0 px-4 pb-28 pt-5 sm:px-7 lg:px-0 lg:pb-12 lg:pt-7"><header className="mb-6 flex items-center justify-between"><div><p className="mb-1 text-xs font-semibold text-[#7c8985]">יום שישי, 11 בספטמבר</p><h1 className="text-[26px] font-black tracking-[-.04em] sm:text-3xl">בוקר טוב, דניאל</h1></div><button aria-label="פרופיל" className="grid size-11 place-items-center rounded-full bg-[#e0c4a4] text-sm font-extrabold ring-4 ring-white/70">דנ</button></header>
   <section aria-label="סיכום כספי" className="mb-5 overflow-hidden rounded-[28px] bg-[#173f3a] p-5 text-white shadow-[0_16px_35px_rgba(23,63,58,.16)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-sm text-white/65">נשאר לך החודש</p><p className="mt-1 text-[34px] font-black">₪3,240</p></div><div className="rounded-2xl bg-white/10 p-3"><WalletCards className="size-6"/></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[57%] rounded-full bg-[#c5e96f]"/></div><div className="mt-3 flex justify-between text-xs text-white/65"><span>נוצלו ₪4,260</span><span>תקציב ₪7,500</span></div><div className="mt-5 grid grid-cols-2 border-t border-white/10 pt-4"><div><p className="text-xs text-white/55">הוצאות היום</p><p className="mt-1 text-lg font-extrabold">₪127</p></div><div className="border-r border-white/10 pr-4"><p className="text-xs text-white/55">הוצאות החודש</p><p className="mt-1 text-lg font-extrabold">₪4,260</p></div></div></section>
   <div className="grid gap-5 xl:grid-cols-[1.08fr_.92fr]"><div className="space-y-5"><section className="panel"><Title title="המשימות שלי" sub={`${completed} מתוך ${tasks.length} הושלמו`} action="לכל המשימות"/><div className="mt-4 space-y-2">{tasks.map(task=><button key={task.id} onClick={()=>toggleTask(task.id)} className="row-item"><span className={`check ${task.done?'done':''}`}>{task.done&&<Check/>}</span><span className="flex-1 text-right"><span className={`block text-sm font-bold ${task.done?'text-[#9aa39f] line-through':''}`}>{task.title}</span>{task.time&&<span className="mt-1 block text-xs text-[#89938f]">{task.time}</span>}</span></button>)}</div><Button onClick={()=>setNotice('טופס משימה חדשה ייפתח כאן')} variant="ghost" className="mt-3 h-10 w-full justify-start rounded-xl text-[#38675d]"><Plus/>משימה חדשה</Button></section>
    <section className="panel"><Title title="פעילות אחרונה" sub="הכל קורה בציר זמן אחד" action="הצג הכל"/><div className="mt-4 divide-y divide-[#ece9e1]">{activity.map(({icon:Icon,title,detail,value,tone})=><div key={title} className="flex items-center gap-3 py-3"><div className={`activity-icon ${tone}`}><Icon/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{title}</p><p className="mt-1 text-xs text-[#8a938f]">{detail}</p></div><span className="text-xs font-extrabold">{value}</span></div>)}</div></section></div>
    <div className="space-y-5"><section className="panel"><div className="section-title"><div><p>ההרגלים של היום</p><span>{habitDone} מתוך {habits.length} הושלמו</span></div><div className="rounded-full bg-[#eff3ee] px-3 py-1 text-xs font-bold text-[#587068]">{habitDone}/{habits.length}</div></div><div className="mt-4 grid grid-cols-3 gap-2">{habits.map(h=><button key={h.id} onClick={()=>toggleHabit(h.id)} className={`habit ${h.done?'active':''}`}><span className="text-2xl">{h.emoji}</span><span className="mt-2 text-xs font-extrabold">{h.title}</span><span className="mt-1 flex items-center gap-1 text-[11px] text-[#77837f]"><Flame className="size-3 text-[#e7884e]"/>{h.streak} ימים</span>{h.done&&<span className="absolute left-2 top-2 grid size-5 place-items-center rounded-full bg-[#173f3a] text-white"><Check className="size-3"/></span>}</button>)}</div></section>
     <section className="panel"><div className="section-title"><div><p>המטרה החודשית</p><span>קרן חופשה ביוון</span></div><b className="rounded-xl bg-[#fff1df] px-2.5 py-1 text-xs text-[#c16e2c]">68%</b></div><div className="mt-5 flex items-center gap-4"><div className="grid size-20 shrink-0 place-items-center rounded-full" style={{background:'conic-gradient(#e8a158 68%,#eeeae1 0)'}}><div className="grid size-16 place-items-center rounded-full bg-white"><Target className="size-6 text-[#d4843f]"/></div></div><div><p className="text-xl font-black">₪3,400</p><p className="mt-1 text-xs text-[#7e8985]">מתוך יעד של ₪5,000</p><p className="mt-3 flex items-center gap-1 text-xs font-bold text-[#3f7568]"><ArrowUpLeft className="size-4"/>נשארו ₪1,600</p></div></div></section>
     <section className="grid grid-cols-2 gap-3"><Quick icon={ArrowDownLeft} title="הוצאה חדשה" sub="תיעוד מהיר" warm onClick={()=>setNotice('הוצאה חדשה תישלח אל ‎/api/expense')}/><Quick icon={CircleDollarSign} title="צ׳ק־אין" sub="איך היה היום?" onClick={()=>setNotice('צ׳ק־אין יומי נוסף')}/></section></div></div>
  </main>
  <nav className="fixed inset-x-0 bottom-0 z-20 mx-auto flex max-w-md items-center justify-around border-t border-black/5 bg-[#fcfbf8]/95 px-3 pb-[max(10px,env(safe-area-inset-bottom))] pt-2 shadow-[0_-12px_28px_rgba(30,40,37,.07)] backdrop-blur-xl lg:hidden" aria-label="ניווט נייד">{[[Home,'היום',true],[WalletCards,'כספים'],[ListTodo,'משימות'],[Flame,'הרגלים'],[Target,'מטרות']].map(([Icon,label,active])=><button key={String(label)} className={`flex min-w-14 flex-col items-center gap-1 text-[10px] font-bold ${active?'text-[#173f3a]':'text-[#87918d]'}`}><span className={active?'rounded-xl bg-[#dcebe5] px-3 py-1.5':'px-3 py-1.5'}><Icon className="size-5"/></span>{String(label)}</button>)}</nav>
  {notice&&<button onClick={()=>setNotice('')} className="fixed bottom-24 left-1/2 z-30 -translate-x-1/2 whitespace-nowrap rounded-2xl bg-[#18211f] px-5 py-3 text-sm font-bold text-white shadow-xl lg:bottom-8">{notice}</button>}
 </div></div>
}

function Title({title,sub,action}:{title:string;sub:string;action:string}){return <div className="section-title"><div><p>{title}</p><span>{sub}</span></div><button className="link-button">{action}<ChevronLeft/></button></div>}
function Quick({icon:Icon,title,sub,warm,onClick}:{icon:typeof ArrowDownLeft;title:string;sub:string;warm?:boolean;onClick:()=>void}){return <button onClick={onClick} className={`quick ${warm?'bg-[#f5dfc7]':'bg-[#dcebe5]'}`}><span className={`quick-icon ${warm?'bg-[#e7a25d]':'bg-[#5f9b89]'}`}><Icon/></span><span><b>{title}</b><small>{sub}</small></span></button>}
