import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';
const timestamps={createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()};
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),displayName:text('display_name').notNull(),timezone:text('timezone').notNull().default('Asia/Jerusalem'),...timestamps});
export const categories=sqliteTable('categories',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),name:text('name').notNull(),color:text('color').notNull().default('#E7A25D'),icon:text('icon'),...timestamps});
export const expenses=sqliteTable('expenses',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),categoryId:text('category_id').references(()=>categories.id),amount:real('amount').notNull(),currency:text('currency').notNull().default('ILS'),description:text('description'),occurredAt:text('occurred_at').notNull(),source:text('source').notNull().default('manual'),externalId:text('external_id'),...timestamps});
export const budgets=sqliteTable('budgets',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),categoryId:text('category_id').references(()=>categories.id),month:text('month').notNull(),amount:real('amount').notNull(),...timestamps});
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),title:text('title').notNull(),status:text('status').notNull().default('inbox'),dueAt:text('due_at'),completedAt:text('completed_at'),...timestamps});
export const habits=sqliteTable('habits',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),title:text('title').notNull(),emoji:text('emoji'),active:integer('active',{mode:'boolean'}).notNull().default(true),...timestamps});
export const habitEntries=sqliteTable('habit_entries',{id:text('id').primaryKey(),habitId:text('habit_id').notNull().references(()=>habits.id),entryDate:text('entry_date').notNull(),value:integer('value').notNull().default(1),...timestamps});
export const goals=sqliteTable('goals',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),title:text('title').notNull(),kind:text('kind').notNull().default('monthly'),targetValue:real('target_value').notNull(),currentValue:real('current_value').notNull().default(0),targetDate:text('target_date'),...timestamps});
export const checkIns=sqliteTable('check_ins',{id:text('id').primaryKey(),profileId:text('profile_id').notNull().references(()=>profiles.id),mood:integer('mood'),note:text('note'),occurredAt:text('occurred_at').notNull(),...timestamps});

export const lifeOwner=sqliteTable("life_owner",{id:integer("id").primaryKey(),passwordHash:text("password_hash").notNull(),salt:text("salt").notNull(),createdAt:text("created_at").notNull()});
export const lifeSessions=sqliteTable("life_sessions",{id:text("id").primaryKey(),expiresAt:integer("expires_at").notNull()});
export const lifeAttempts=sqliteTable("life_attempts",{id:text("id").primaryKey(),count:integer("count").notNull(),expiresAt:integer("expires_at").notNull()});

export const lifeRecords=sqliteTable('life_records',{id:text('id').primaryKey(),kind:text('kind').notNull(),data:text('data').notNull(),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),deletedAt:text('deleted_at')});
